name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 91.229.10.145
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /var/www/be-go-flush
            cd /var/www/be-go-flush

            # Клонируем или обновляем исходники
            if [ -d ".git" ]; then git pull; else git clone https://github.com/caseapia/be-go-flush.git .; fi

            # Билд проекта
            /usr/bin/go build -o server_bin main.go

            # Очистка: удаляем всё, кроме бинарника и .env (если есть)
            find . -maxdepth 1 ! -name 'server_bin' ! -name '.env' ! -name '.' -exec rm -rf {} +

            # Перезапуск (лучше использовать systemd, см. ниже)
            pkill server_bin || true
            nohup ./server_bin > log.txt 2>&1 &
